language: objective-c
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

  - IOS_DESTANATION="platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72,OS=10.2"
before_install:
  - gem install xcpretty-travis-formatter
script:
  - set -o pipefail
  - xcodebuild -project Marshroute.xcodeproj -scheme "Marshroute" -destination "$IOS_DESTANATION" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" test | xcpretty -f `xcpretty-travis-formatter`
