language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

  - IOS_DESTANATION="platform=iOS Simulator,OS=10.3,name=iPhone 7 Plus"
before_install:
  - gem install xcpretty-travis-formatter
script:
  - set -o pipefail
  - set -e
  - set -x
  - pushd "Example" > /dev/null
  - pod install
  - xcodebuild -workspace NavigationDemo.xcworkspace -scheme "Marshroute" -destination "$IOS_DESTANATION" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean test | xcpretty -f `xcpretty-travis-formatter`
  - popd > /dev/null
