language: objective-c
osx_image: xcode11_3_1

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_DESTANATION="platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro"
before_install:
  - gem install xcpretty-travis-formatter
script:
  - set -o pipefail
  - xcodebuild -workspace "Example/NavigationDemo.xcworkspace" -scheme "NavigationDemo" -destination "$IOS_DESTANATION" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -enableCodeCoverage YES clean test | xcpretty -f `xcpretty-travis-formatter`
after_success:
  - bash <(curl -s https://codecov.io/bash)
